name: Build (Common)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM Packages (Common)
        run: npm install
        working-directory: ./modules/common
      - name: Build Common (NPM)
        run: npm run build
        working-directory: ./modules/common
      - name: Create source code tarbell
        run: git archive -o modules/common/dist/source.tar.gz HEAD
      - name: Copy License to output dist
        run: cp LICENSE.md modules/common/dist
      - name: Upload Output
        uses: actions/upload-artifact@main
        with:
          name: common
          path: modules/common/dist